// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (customer_id) 
VALUES ($1) RETURNING id, customer_id, created_at
`

func (q *Queries) CreateOrder(ctx context.Context, customerID int64) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, customerID)
	var i Order
	err := row.Scan(&i.ID, &i.CustomerID, &i.CreatedAt)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (order_id, product_id, quantity, price_cents)
VALUES ($1, $2, $3, $4) RETURNING id, order_id, product_id, quantity, price_cents
`

type CreateOrderItemParams struct {
	OrderID    int64 `json:"order_id"`
	ProductID  int64 `json:"product_id"`
	Quantity   int32 `json:"quantity"`
	PriceCents int32 `json:"price_cents"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.PriceCents,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.Quantity,
		&i.PriceCents,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products(name, description, price_in_cents, quantity) 
VALUES ($1, $2, $3, $4) RETURNING id, name, description, price_in_cents, quantity, created_at
`

type CreateProductParams struct {
	Name         string      `json:"name"`
	Description  pgtype.Text `json:"description"`
	PriceInCents int32       `json:"price_in_cents"`
	Quantity     int32       `json:"quantity"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.Description,
		arg.PriceInCents,
		arg.Quantity,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PriceInCents,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const decrementProductQuantity = `-- name: DecrementProductQuantity :exec
UPDATE products
SET quantity = quantity - $2
WHERE id = $1
`

type DecrementProductQuantityParams struct {
	ID       int64 `json:"id"`
	Quantity int32 `json:"quantity"`
}

func (q *Queries) DecrementProductQuantity(ctx context.Context, arg DecrementProductQuantityParams) error {
	_, err := q.db.Exec(ctx, decrementProductQuantity, arg.ID, arg.Quantity)
	return err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const filterProducts = `-- name: FilterProducts :many
SELECT id, name, description, price_in_cents, quantity, created_at FROM products
WHERE
    ($1::text IS NULL OR name ILIKE '%' || $1::text || '%') AND
    ($2::integer IS NULL OR price_in_cents >= $2::integer) AND
    ($3::integer IS NULL OR price_in_cents <= $3::integer) AND
    ($4::integer IS NULL OR quantity >= $4::integer) AND
    ($5::integer IS NULL OR quantity <= $5::integer)
`

type FilterProductsParams struct {
	Name        pgtype.Text `json:"name"`
	MinPrice    pgtype.Int4 `json:"min_price"`
	MaxPrice    pgtype.Int4 `json:"max_price"`
	MinQuantity pgtype.Int4 `json:"min_quantity"`
	MaxQuantity pgtype.Int4 `json:"max_quantity"`
}

func (q *Queries) FilterProducts(ctx context.Context, arg FilterProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, filterProducts,
		arg.Name,
		arg.MinPrice,
		arg.MaxPrice,
		arg.MinQuantity,
		arg.MaxQuantity,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.PriceInCents,
			&i.Quantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderById = `-- name: GetOrderById :one
SELECT id, customer_id, created_at FROM orders WHERE id = $1
`

func (q *Queries) GetOrderById(ctx context.Context, id int64) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderById, id)
	var i Order
	err := row.Scan(&i.ID, &i.CustomerID, &i.CreatedAt)
	return i, err
}

const getOrderItemsByOrderId = `-- name: GetOrderItemsByOrderId :many
SELECT id, order_id, product_id, quantity, price_cents FROM order_items WHERE order_id = $1
`

func (q *Queries) GetOrderItemsByOrderId(ctx context.Context, orderID int64) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, getOrderItemsByOrderId, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.Quantity,
			&i.PriceCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, description, price_in_cents, quantity, created_at FROM products WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PriceInCents,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, description, price_in_cents, quantity, created_at FROM products
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.PriceInCents,
			&i.Quantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET name = $2, description = $3, price_in_cents = $4, quantity = $5
WHERE id = $1 RETURNING id, name, description, price_in_cents, quantity, created_at
`

type UpdateProductParams struct {
	ID           int64       `json:"id"`
	Name         string      `json:"name"`
	Description  pgtype.Text `json:"description"`
	PriceInCents int32       `json:"price_in_cents"`
	Quantity     int32       `json:"quantity"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.PriceInCents,
		arg.Quantity,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PriceInCents,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}
