// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"
)

type Querier interface {
	CreateOrder(ctx context.Context, customerID int64) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	DecrementProductQuantity(ctx context.Context, arg DecrementProductQuantityParams) error
	DeleteProduct(ctx context.Context, id int64) error
	FilterProducts(ctx context.Context, arg FilterProductsParams) ([]Product, error)
	GetOrderById(ctx context.Context, id int64) (Order, error)
	GetOrderItemsByOrderId(ctx context.Context, orderID int64) ([]OrderItem, error)
	GetProductByID(ctx context.Context, id int64) (Product, error)
	IncrementProductQuantity(ctx context.Context, arg IncrementProductQuantityParams) error
	ListProducts(ctx context.Context) ([]Product, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
}

var _ Querier = (*Queries)(nil)
