-- +goose Up
ALTER TABLE products DROP COLUMN IF EXISTS description;
ALTER TABLE products ADD COLUMN IF NOT EXISTS category TEXT NOT NULL DEFAULT 'other'
CHECK (category IN ('ELECTRONICS', 'CLOTHING', 'HOME', 'BOOKS','FOOD', 'other'));


ALTER TABLE orders ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'PENDING'
CHECK (status IN ('PENDING', 'SHIPPED', 'DELIVERED', 'CANCELED'));

-- +goose Down
ALTER TABLE orders DROP COLUMN IF EXISTS status;

ALTER TABLE products DROP COLUMN IF EXISTS category;
ALTER TABLE products ADD COLUMN IF NOT EXISTS description TEXT;
